apiVersion: v1
kind: Pod
metadata:
  name: jump-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - args:
    - sh
    image: nigelpoulton/curl:1.0
    name: jump-pod
    tty: true
    stdin: true